language: java
sudo: false # faster builds
before_script: cd bundle
script: mvn -Dmaven.test.failure.ignore=true clean verify jacoco:report
after_script: mvn coveralls:report # Sending jacoco report